### ISSUE TITLE
Search: option for exact match

### ISSUE THREAD

**Issue by AngieHinrichs** [theosanderson/taxonium#213]
Sometimes I'd like to search for a name that would have an exact match but has multiple prefix matches, or a lineage that would match one little branch in the tree but matches half the tree as a prefix like B.1.6 (matching B.1.617.2!).  It would be very helpful to have a checkbox for 'Exact match', so when I'm trying to find B.1.6 or AY.3 I can actually find it.  :)  Thanks for all the recent improvements to taxonium, it's amazingly powerful!

**Comment by theosanderson** [comment]
Thanks for this!

Ah, so funnily enough that's how lineage search works on Cov2Tree itself, but not for custom trees.

The reason it works on Cov2Tree is because it is configured with a config file: https://github.com/theosanderson/taxonium/blob/master/taxonium_backend/config_public.json

There's a few ways to supply that config file - one is in the usher_to_taxonium `--config`, another is after the fact with a `&configUrl=` in the URL, or with `&config=` with a url encoded JSON string.

None of that is to say I shouldn't think about making this work in a simpler way just with a checkbox as you suggest! Thanks for the feedback

**Comment by theosanderson** [comment]
(oops I'd forgotten to merge, should be there now)

**Comment by AngieHinrichs** [comment]
Awesome, thanks so much!  Great to have the multiple option too!

**Comment by theosanderson** [comment]
@all-contributors Please add @AngieHinrichs for ideas and data

**Comment by AngieHinrichs** [comment]
Thank you Theo!  😃
