### ISSUE TITLE
Default colors

### ISSUE THREAD

**Issue by amusheg** [theosanderson/taxonium#297]
Taxonium is INCREDIBLY useful for exploring some large phylogenetic trees I have. I have one request: would it be possible to change the default color scheme? Right now, I'm trying to color the tips by a trait that has three states, and the three colors it uses are shades of purple that are so close to each other as to be almost indistinguishable. See below:
<img width="283" alt="Screen Shot 2022-06-28 at 4 37 13 PM" src="https://user-images.githubusercontent.com/31630283/176281661-56f706f3-d94d-4543-aa0a-cd0a561baf0f.png">

It would be great if it defaulted to colors with higher contrast to each other.

**Comment by theosanderson** [comment]
Hi there,

Thanks for raising this issue. The way that Taxonium handles colours by default is that they are computed as a hash of the text they represent. That has advantages, because it means that they are consistent over time. But collisions can occur as they seem to have here. If you're able to share it would be helpful to know what your state values are in case there's a systematic thing that may recur for other people.

There is a way that you can specify custom colors. You need to supply a config, with a `colorMapping` which maps the string values you want to colors as a list of RGB values.

```
{
  "AY.4": [
    255,
    0,
    0
  ],
  "B.1.1.7": [
    0,
    0,
    255
  ]
}
```

There are a few ways to supply the config, one is just in the URL:
https://cov2tree.org/?config={"colorMapping":{"AY.4":[255,0,0],"B.1.1.7":[0,0,255]}}

You can also supply a path to a config JSON file in the URL instead as we do with mpxTree

https://taxonium.org/?protoUrl=https%3A%2F%2Fmpx-tree.vercel.app%2Fmpx.jsonl.gz&configUrl=https%3A%2F%2Fmpx-tree.vercel.app%2Fconfig.json&taxonColumn=strain&color=%7B%22field%22%3A%22meta_clade%22%7D

That JSON file can contain a colorMapping element.

You can also bake this config into the Taxonioum JSONL file using the ``-config_json` parameter.

Let me know if you have issues.

**Comment by amusheg** [comment]
Oh, that's interesting. My traits are "North America", "South America" and "Caribbean". Adding the config to the URL seems like a fine workaround but will I need to get rid of the spaces in the region names to be able to format that?

**Comment by theosanderson** [comment]
I added these to the hard-coding (possibly with ugly arbitrary colours). I added a bit more information on colour configuration to https://docs.taxonium.org/en/latest/advanced.html . Going to close this for now but feel free to reply if you have issues.

**Comment by amusheg** [comment]
Thank you for this (and for the useful tool)!
