### ISSUE TITLE
Allow user to root at selected internal branch?

### ISSUE THREAD

**Issue by singing-scientist** [theosanderson/taxonium#447]
Any plans to allow the user to re-root the tree at a selected internal branch? Thanks so much for the great tool!

**Comment by theosanderson** [comment]
Thanks for the issue. Because of the way Taxonium is set up to allow 10M node trees, it is quite reliant on an architecture where positions are precomputed. Therefore this feature is relatively unlikely, although given that Newick trees are laid out at runtime it's definitely not impossible -- but it's not on the roadmap atm, sorry.
