### ISSUE TITLE
bug: newlines in Newick break metadata lookup

### ISSUE THREAD

**Issue by GuilhemSempere** [theosanderson/taxonium#467]
It must be myself doing something wrong but I can't get my metadata to be taken into account (doesn't appear in the tooltip when mousing over nodes)

Also... I'd like to know if it's possible to use the colorMapping feature on a per-metadata field basis, rather than specifying a color for each and every node.

Thanks if you can help. And for the great work!
[newick+metadata.zip](https://github.com/theosanderson/taxonium/files/10491347/newick%2Bmetadata.zip)

**Comment by theosanderson** [comment]
Thanks for reporting this and providing your data! Your Newick has lots of newlines in it, which mean that Taxonium thinks your nodes are called "my_node\n" instead of "my_node". I will fix this so that these trees are supported, but in the meantime you can just use find and replace to remove the newlines from your tree file, like 
[_nj.230124221522967.o.nh.txt](https://github.com/theosanderson/taxonium/files/10491422/_nj.230124221522967.o.nh.txt).

The colorMapping is not for every node. You are simply providing a color for the value, e.g. `{"XI-adm":[255,0,0],.....}`

**Comment by GuilhemSempere** [comment]
Many thanks for your quick response! It's great if such files can be supported out of the box as this is how they are produced by the online mafft service. Is the fix meant to be applied to the live https://taxonium.org/ site already? It doesn't seem so to me

**Comment by theosanderson** [comment]
> Is the fix meant to be applied to the live https://taxonium.org/ site already? It doesn't seem so to me

It is. I've just checked with the files from your ZIP above and I get:
![image](https://user-images.githubusercontent.com/19732295/214540625-258c49d5-ef48-4eb2-8f56-95846d658bdb.png)

Please could you try the exact files from the zip and check if they work for you, if not then try clearing your cache. If you still have issues, let me know and if you have issues with other files also let me know.

Thanks

**Comment by GuilhemSempere** [comment]
You are right I was using the wrong tree. Many thanks again
