### ISSUE TITLE
Joint conditions

### ISSUE THREAD

**Issue by chaoran-chen** [theosanderson/taxonium#87]
It would be great if it would be possible to narrow down a query further and, for example, search for Deltas with a certain mutation in a particular country!

**Comment by theosanderson** [comment]
Thanks @chaoran-chen -- agree this is an important feature

**Comment by chaoran-chen** [comment]
Hi @theosanderson! I'd be interested in adding a Taxonium integration in mpox-spectrum as well and was just wondering whether you plan to implement this feature any time soon. It would be really useful! :)

**Comment by theosanderson** [comment]
Hi, it's high on the list, and definitely doable - but there's other stuff on the list too.. can't give a timetable right now sorry for the frustration but definitely still planned

**Comment by chaoran-chen** [comment]
Thanks for the feedback! I'll be looking forward to it.

**Comment by theosanderson** [comment]
OK, you gave me some extra impetus on this :) This should be in with #234 .

So we can do [this](https://mpx.taxonium.org/?srch=%5B%7B%22key%22%3A%22c5mpx7egspw%22%2C%22type%22%3A%22boolean%22%2C%22method%22%3A%22boolean%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%2C%22subspecs%22%3A%5B%7B%22key%22%3A%224uaa9trvxso%22%2C%22type%22%3A%22meta_clade%22%2C%22method%22%3A%22text_match%22%2C%22text%22%3A%22WA%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%22ck25tiaa5sj%22%2C%22type%22%3A%22meta_region%22%2C%22method%22%3A%22text_match%22%2C%22text%22%3A%22Africa%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%7D%5D%2C%22boolean_method%22%3A%22and%22%7D%2C%7B%22key%22%3A%22y9nzxscxiwa%22%2C%22type%22%3A%22boolean%22%2C%22method%22%3A%22boolean%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%2C%22subspecs%22%3A%5B%7B%22key%22%3A%22wdyaflgh1zf%22%2C%22type%22%3A%22meta_region%22%2C%22method%22%3A%22text_match%22%2C%22text%22%3A%22Africa%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%221de9wnin7gp%22%2C%22type%22%3A%22boolean%22%2C%22method%22%3A%22boolean%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%2C%22subspecs%22%3A%5B%7B%22key%22%3A%22j9p90z1akod%22%2C%22type%22%3A%22meta_country%22%2C%22method%22%3A%22text_match%22%2C%22text%22%3A%22Nigeria%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%22i4aizrye7zk%22%2C%22type%22%3A%22meta_country%22%2C%22method%22%3A%22text_match%22%2C%22text%22%3A%22Cote%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%7D%5D%2C%22boolean_method%22%3A%22not%22%7D%5D%2C%22boolean_method%22%3A%22and%22%7D%5D&enabled=%7B%22aa1%22%3Atrue%2C%22c5mpx7egspw%22%3Atrue%2C%22y9nzxscxiwa%22%3Atrue%7D)

<img width="436" alt="image" src="https://user-images.githubusercontent.com/19732295/170392312-9082c881-6476-49c0-9448-d7b0f04ac051.png">

A few caveats:
- I need to refactor some stuff to reduce the URL length by avoiding all the redundant stuff that is there at the moment, this might change some stuff in the future
- Right now we don't have a way to search by genotype of a final node, just for the internal node at which a mutation happens. That limits how actually useful this is because internal nodes don't have metadata annotations (atm) and tip nodes don't have mutation annotations (often). I plan to add the ability to search by genotype in future.
- Similarly, NOT is not that useful on its own, as internal nodes satisfy almost any NOT condition. We can fix this with a search that returns internal or tip nodes.

**Comment by chaoran-chen** [comment]
Excellent! I'll integrate it into mpox- and cov-spectrum very soon.

**Comment by theosanderson** [comment]
OK we now have a search by Genotype - so that can be combined with Country searches etc. These searches may be slow and unreliable though, not sure yet.

**Comment by chaoran-chen** [comment]
Here it is for mpox-spectrum!

![image](https://user-images.githubusercontent.com/18666552/170869679-ee6d7d9b-2dbd-47b6-b4e3-14a1aa8261c7.png)

Here is the corresponding code. Hope it's alright. https://github.com/cevo-public/mpox-spectrum-website/blob/main/src/services/external-integrations/TaxoniumIntegration.ts

(What are your update intervals?)

**Comment by theosanderson** [comment]
Amazing stuff. (An "integrations" feature for Taxonium to link out from lineages is still on my list).

Update intervals are atm ad-hoc as I'm trying to keep an eye on things but I just pushed an update. (I do get the point that we want to keep things synced up!)

Thanks for all the collaboration!
